#!/usr/bin/env bash
#
# Deploy CloudFormation stack to production.

bucket="api.fractal.parts"

sam package \
    --output-template-file packaged.yml \
    --s3-bucket $bucket

sam deploy \
    --template-file packaged.yml \
    --stack-name fractal-parts \
    --capabilities CAPABILITY_IAM
