#!/usr/bin/env bash
#
# Run the API locally.

docker run -p 3306:3306 \
       -e MYSQL_ROOT_PASSWORD=password \
       -e MYSQL_DATABASE=database \
       -e MYSQL_USER=user \
       -e MYSQL_PASSWORD=password \
       -d mysql:5.6

sam local start-api
