AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: fractal.parts

Globals:
  Function:
    Runtime: nodejs8.10
    CodeUri: functions/
    AutoPublishAlias: live
    Environment:
      Variables:
        TABLE_NAME: !Ref FractalTable

Resources:
  GetFractalsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: list.handle
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FractalTable
      Events:
        GetFractals:
          Type: Api
          Properties:
            Path: /fractals
            Method: get
  PostFractalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create.handle
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FractalTable
      Events:
        PostFractal:
          Type: Api
          Properties:
            Path: /fractals
            Method: post
  GetFractalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get.handle
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FractalTable
      Events:
        GetFractal:
          Type: Api
          Properties:
            Path: /fractals/{id}
            Method: get
  FractalTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FractalTable
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
