AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: fractal.parts

Globals:
  Function:
    Runtime: nodejs8.10
    CodeUri: functions/
    AutoPublishAlias: live

Resources:
  GetFractalsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: list.handle
      Events:
        GetFractals:
          Type: Api
          Properties:
            Path: /fractals
            Method: get
  PostFractalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create.handle
      Events:
        PostFractal:
          Type: Api
          Properties:
            Path: /fractals
            Method: post
  GetFractalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get.handle
      Events:
        GetFractal:
          Type: Api
          Properties:
            Path: /fractals/{key}
            Method: get
